name: flutter_google_map
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  bloc: ^9.2.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  firebase_auth: ^6.5.1
  firebase_core: ^4.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gap: ^1.2.0
  flutter_map: ^8.3.0
  flutter_native_splash: ^2.4.7
  flutter_polyline_points: ^3.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  flutter_typeahead: ^6.0.0
  geolocator: ^14.0.2
  get_it: ^9.2.1
  google_maps_flutter: ^2.17.0
  latlong2: ^0.9.1
  pin_code_fields: ^9.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svgs/