// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ6YSdKJFOyKH0Rimk0sAtZ0eWLyoN6HQ',
    appId: '1:93546838485:web:7498b611d307416b77255c',
    messagingSenderId: '93546838485',
    projectId: 'delivery-bd7d6',
    authDomain: 'delivery-bd7d6.firebaseapp.com',
    storageBucket: 'delivery-bd7d6.firebasestorage.app',
    measurementId: 'G-R1LFT036W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fce1zsizXLXJxc-P8ipPzGt2CCzIti8',
    appId: '1:93546838485:android:a9a1e5d503cd957b77255c',
    messagingSenderId: '93546838485',
    projectId: 'delivery-bd7d6',
    storageBucket: 'delivery-bd7d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqAyYvREU0WS57ZoA1MOSYTeAxG92Lp18',
    appId: '1:93546838485:ios:e205cc5a7d92f91a77255c',
    messagingSenderId: '93546838485',
    projectId: 'delivery-bd7d6',
    storageBucket: 'delivery-bd7d6.firebasestorage.app',
    iosBundleId: 'com.example.flutterGoogleMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqAyYvREU0WS57ZoA1MOSYTeAxG92Lp18',
    appId: '1:93546838485:ios:e205cc5a7d92f91a77255c',
    messagingSenderId: '93546838485',
    projectId: 'delivery-bd7d6',
    storageBucket: 'delivery-bd7d6.firebasestorage.app',
    iosBundleId: 'com.example.flutterGoogleMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ6YSdKJFOyKH0Rimk0sAtZ0eWLyoN6HQ',
    appId: '1:93546838485:web:31580945d9b6930477255c',
    messagingSenderId: '93546838485',
    projectId: 'delivery-bd7d6',
    authDomain: 'delivery-bd7d6.firebaseapp.com',
    storageBucket: 'delivery-bd7d6.firebasestorage.app',
    measurementId: 'G-XYGJ00FDYF',
  );
}
